---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: keepalived
  namespace: keepalived
  labels:
    application: keepalived
spec:
  selector:
    matchLabels:
      application: keepalived
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: keepalived
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      hostNetwork: true
      containers:
      - name: keepalived
        image: geoffh1977/keepalived
        env:
          - name: PASSWORD
            value: vipshare
          - name: VIRTUAL_IP
            value: '192.168.1.250'
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
